const kelimeler = [
    { kelime: "telefon", ipucu: "Çoğunlukla iletişim kurmak  kullanılan taşınabilir  cihaz." },
    { kelime: "kitap", ipucu: "Birçok sayfası olan ve bilgi veya hikaye içeren basılı veya dijital yayın." },
    { kelime: "araba", ipucu: "Motorlu taşıt, özellikle dört tekerlekli ve özel veya ticari kullanım için tasarlanmış olan." },
    { kelime: "ev", ipucu: "Bir kişinin yaşamak veya barınmak için kullandığı yer." },
    { kelime: "bilgisayar", ipucu: "Verileri işlemek, depolamak ve iletmek için tasarlanmış elektronik bir cihaz." },
    { kelime: "güneş", ipucu: "Gündüz gökyüzünde ışık ve ısı sağlayan yıldız." },
    { kelime: "deniz", ipucu: "Büyük tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "kuş", ipucu: "Genellikle uçan, tüylü ve yumurtlayan omurgalı hayvan." },
    { kelime: "ayakkabı", ipucu: "Ayakları giyinmek veya korumak için giyilen giysi." },
    { kelime: "kalem", ipucu: "Yazı yazmak veya çizim yapmak için kullanılan araç." },
    { kelime: "gözlük", ipucu: "Görme yeteneğini düzeltmek veya korumak için kullanılan optik araç." },
    { kelime: "yıldız", ipucu: "Gökyüzünde parlak nokta şeklinde görünen astronomik nesne." },
    { kelime: "hastane", ipucu: "Sağlık hizmetleri ve tıbbi tedavi sunan sağlık kurumu." },
    { kelime: "oyun", ipucu: "Eğlenmek, rekabet etmek veya amaçlı etkinliklerle zaman geçirmek için yapılan faaliyet." },
    { kelime: "kuşatma", ipucu: "Bir şehri veya kaleyi kuşatarak kontrol altına alma eylemi." },
    { kelime: "güvenlik", ipucu: "Tehlikelere karşı koruma ve emniyet sağlama durumu." },
    { kelime: "dil", ipucu: "Düşünceleri ve duyguları ifade etmek ve iletmek için kullanılan sistem." },
    { kelime: "gece", ipucu: "Güneşin batışından günün doğuşuna kadar süren dönem." },
    { kelime: "yazılım", ipucu: "Bilgisayarın çalışması için talimatları içeren programlar." },
    { kelime: "kitaplık", ipucu: "Kitapları saklamak ve düzenlemek için kullanılan mobilya." },
    { kelime: "öğrenci", ipucu: "Okul veya üniversitede eğitim alan kişi." },
    { kelime: "orman", ipucu: "Ağaçlarla kaplı büyük doğal alan." },
    { kelime: "şapka", ipucu: "Başı korumak veya süslemek için giyilen başlık." },
    { kelime: "kahve", ipucu: "Kavrulmuş kahve çekirdeklerinden yapılan içecek." },
    { kelime: "çiçek", ipucu: "Bitkilerin rengarenk ve güzel görünümlü organı." },
    { kelime: "bulut", ipucu: "Gökyüzünde görülen su damlacıklarının veya buz kristallerinin topluluğu." },
    { kelime: "rüya", ipucu: "Uyurken görülen hayal veya düş." },
    { kelime: "şeker", ipucu: "Tatlı tadı olan besin veya madde." },
    { kelime: "kedi", ipucu: "Küçük, tüylü ve dört ayaklı evcil hayvan." },
    { kelime: "uyku", ipucu: "Bilinçli olmayan bir durumda olma ve dinlenme zamanı." },
    { kelime: "deniz", ipucu: "Tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "kum", ipucu: "Toprak parçacıklarının birikmesi sonucu oluşan ince tanecikli madde." },
    { kelime: "göl", ipucu: "Genellikle su birikintisinin yer aldığı doğal veya yapay alan." },
    { kelime: "kalem", ipucu: "Yazı yazmak veya çizim yapmak için kullanılan araç." },
    { kelime: "futbol", ipucu: "Topun bir takım arkadaşları arasında rakip takımın kalesine sokulması oyunu." },
    { kelime: "aşk", ipucu: "Yoğun duygusal bir bağ ve sevgi durumu." },
    { kelime: "ses", ipucu: "Hava titreşimleri yoluyla duyulabilen ses veya seslerin oluşturduğu olay." },
    { kelime: "saat", ipucu: "Zamanı ölçmek için kullanılan cihaz." },
    { kelime: "yıldırım", ipucu: "Elektrik deşarjı nedeniyle oluşan parlak ve ani ışık." },
    { kelime: "kale", ipucu: "Genellikle bir şehri veya stratejik bir alanı korumak için yapılan yapı." },
    { kelime: "gemi", ipucu: "Denizde seyahat etmek için kullanılan büyük su aracı." },
    { kelime: "müzik", ipucu: "Seslerin ve ritimlerin düzenlenmesi ve ifade edilmesi sanatı." },
    { kelime: "pazar", ipucu: "Genellikle ticaret ve alışverişin yapıldığı belirli gün ve yer." },
    { kelime: "kuş", ipucu: "Genellikle uçan, tüylü ve yumurtlayan omurgalı hayvan." },
    { kelime: "gece", ipucu: "Güneşin batışından günün doğuşuna kadar süren dönem." },
    { kelime: "buz", ipucu: "Su soğuyup donduğunda oluşan katı durum." },
    { kelime: "güneş", ipucu: "Gündüz gökyüzünde ışık ve ısı sağlayan yıldız." },
    { kelime: "yol", ipucu: "Bir yerden diğerine ulaşmak için kullanılan genellikle açık alan." },
    { kelime: "oyun", ipucu: "Eğlenmek, rekabet etmek veya amaçlı etkinliklerle zaman geçirmek için yapılan faaliyet." },
    { kelime: "yemek", ipucu: "Yemek pişirmek ve yemek için kullanılan besinlerin genel adı." },
    { kelime: "ağaç", ipucu: "Odun veya yaprakları olan büyük bitki." },
    { kelime: "yazılım", ipucu: "Bilgisayarın çalışması için talimatları içeren programlar." },
    { kelime: "kitap", ipucu: "Birçok sayfası olan ve bilgi veya hikaye içeren basılı veya dijital yayın." },
    { kelime: "top", ipucu: "Genellikle yuvarlak ve çeşitli oyunlar için kullanılan spor aracı." },
    { kelime: "bulut", ipucu: "Gökyüzünde görülen su damlacıklarının veya buz kristallerinin topluluğu." },
    { kelime: "öğrenci", ipucu: "Okul veya üniversitede eğitim alan kişi." },
    { kelime: "hastane", ipucu: "Sağlık hizmetleri ve tıbbi tedavi sunan sağlık kurumu." },
    { kelime: "oyuncak", ipucu: "Eğlence veya oyun amaçlı kullanılan nesne veya araç." },
    { kelime: "kedi", ipucu: "Küçük, tüylü ve dört ayaklı evcil hayvan." },
    { kelime: "ses", ipucu: "Hava titreşimleri yoluyla duyulabilen ses veya seslerin oluşturduğu olay." },
    { kelime: "gözlük", ipucu: "Görme yeteneğini düzeltmek veya korumak için kullanılan optik araç." },
    { kelime: "rüya", ipucu: "Uyurken görülen hayal veya düş." },
    { kelime: "balık", ipucu: "Su içinde yaşayan omurgalı hayvanlar." },
    { kelime: "uçak", ipucu: "Hava yoluyla seyahat etmek için kullanılan hava aracı." },
    { kelime: "kum", ipucu: "Toprak parçacıklarının birikmesi sonucu oluşan ince tanecikli madde." },
    { kelime: "şarkı", ipucu: "Sesli bir şekilde ifade edilen müzik ve sözlerin birleşimi." },
    { kelime: "saat", ipucu: "Zamanı ölçmek için kullanılan cihaz." },
    { kelime: "çiçek", ipucu: "Bitkilerin rengarenk ve güzel görünümlü organı." },
    { kelime: "aşk", ipucu: "Yoğun duygusal bir bağ ve sevgi durumu." },
    { kelime: "yemek", ipucu: "Yemek pişirmek ve yemek için kullanılan besinlerin genel adı." },
    { kelime: "deniz", ipucu: "Tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "futbol", ipucu: "Topun bir takım arkadaşları arasında rakip takımın kalesine sokulması oyunu." },
    { kelime: "çanta", ipucu: "Taşımak için kullanılan torba benzeri eşya." },
    { kelime: "televizyon", ipucu: "Görüntü ve sesleri evde yayınlayan elektronik cihaz." },
    { kelime: "kelebek", ipucu: "Gündüz uçan, renkli ve kanatlı böcek." },
    { kelime: "pencere", ipucu: "Duvar veya çatıda açılan camlı boşluk." },
    { kelime: "yıldırım", ipucu: "Elektrik deşarjı nedeniyle oluşan parlak ve ani ışık." },
    { kelime: "kale", ipucu: "Genellikle bir şehri veya stratejik bir alanı korumak için yapılan yapı." },
    { kelime: "gemi", ipucu: "Denizde seyahat etmek için kullanılan büyük su aracı." },
    { kelime: "müzik", ipucu: "Seslerin ve ritimlerin düzenlenmesi ve ifade edilmesi sanatı." },
    { kelime: "pazar", ipucu: "Genellikle ticaret ve alışverişin yapıldığı belirli gün ve yer." },
    { kelime: "kuş", ipucu: "Genellikle uçan, tüylü ve yumurtlayan omurgalı hayvan." },
    { kelime: "gece", ipucu: "Güneşin batışından günün doğuşuna kadar süren dönem." },
    { kelime: "buz", ipucu: "Su soğuyup donduğunda oluşan katı durum." },
    { kelime: "güneş", ipucu: "Gündüz gökyüzünde ışık ve ısı sağlayan yıldız." },
    { kelime: "yol", ipucu: "Bir yerden diğerine ulaşmak için kullanılan genellikle açık alan." },
    { kelime: "oyun", ipucu: "Eğlenmek, rekabet etmek veya amaçlı etkinliklerle zaman geçirmek için yapılan faaliyet." },
    { kelime: "yemek", ipucu: "Yemek pişirmek ve yemek için kullanılan besinlerin genel adı." },
    { kelime: "ağaç", ipucu: "Odun veya yaprakları olan büyük bitki." },
    { kelime: "yazılım", ipucu: "Bilgisayarın çalışması için talimatları içeren programlar." },
    { kelime: "kitap", ipucu: "Birçok sayfası olan ve bilgi veya hikaye içeren basılı veya dijital yayın." },
    { kelime: "top", ipucu: "Genellikle yuvarlak ve çeşitli oyunlar için kullanılan spor aracı." },
    { kelime: "bulut", ipucu: "Gökyüzünde görülen su damlacıklarının veya buz kristallerinin topluluğu." },
    { kelime: "öğrenci", ipucu: "Okul veya üniversitede eğitim alan kişi." },
    { kelime: "hastane", ipucu: "Sağlık hizmetleri ve tıbbi tedavi sunan sağlık kurumu." },
    { kelime: "oyuncak", ipucu: "Eğlence veya oyun amaçlı kullanılan nesne veya araç." },
    { kelime: "kedi", ipucu: "Küçük, tüylü ve dört ayaklı evcil hayvan." },
    { kelime: "ses", ipucu: "Hava titreşimleri yoluyla duyulabilen ses veya seslerin oluşturduğu olay." },
    { kelime: "gözlük", ipucu: "Görme yeteneğini düzeltmek veya korumak için kullanılan optik araç." },
    { kelime: "rüya", ipucu: "Uyurken görülen hayal veya düş." },
    { kelime: "balık", ipucu: "Su içinde yaşayan omurgalı hayvanlar." },
    { kelime: "uçak", ipucu: "Hava yoluyla seyahat etmek için kullanılan hava aracı." },
    { kelime: "kum", ipucu: "Toprak parçacıklarının birikmesi sonucu oluşan ince tanecikli madde." },
    { kelime: "şarkı", ipucu: "Sesli bir şekilde ifade edilen müzik ve sözlerin birleşimi." },
    { kelime: "saat", ipucu: "Zamanı ölçmek için kullanılan cihaz." },
    { kelime: "çiçek", ipucu: "Bitkilerin rengarenk ve güzel görünümlü organı." },
    { kelime: "aşk", ipucu: "Yoğun duygusal bir bağ ve sevgi durumu." },
    { kelime: "yemek", ipucu: "Yemek pişirmek ve yemek için kullanılan besinlerin genel adı." },
    { kelime: "deniz", ipucu: "Tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "futbol", ipucu: "Topun bir takım arkadaşları arasında rakip takımın kalesine sokulması oyunu." },
    { kelime: "çanta", ipucu: "Taşımak için kullanılan torba benzeri eşya." },
    { kelime: "televizyon", ipucu: "Görüntü ve sesleri evde yayınlayan elektronik cihaz." },
    { kelime: "öğretmen", ipucu: "Eğitim veren ve öğrencilere rehberlik eden kişi." },
    { kelime: "araba", ipucu: "Motorlu taşıt, özellikle dört tekerlekli ve özel veya ticari kullanım için tasarlanmış olan." },
    { kelime: "çikolata", ipucu: "Kakao ve şekerden yapılan lezzetli tatlı." },
    { kelime: "elektrik", ipucu: "Enerjinin taşınmasını ve kullanılmasını sağlayan fiziksel kuvvet." },
{ kelime: "teknoloji", ipucu: "Bilimsel bilgi ve yöntemlerin pratik uygulamalarıyla ilgilenen alan." },
{ kelime: "felsefe", ipucu: "Dünya ve insanın varoluşunu, bilgiyi ve değerleri anlamaya çalışan disiplin." },
{ kelime: "universite", ipucu: "Yüksek öğrenim kurumu, akademik programlar sunar." },
{ kelime: "karakter", ipucu: "Bir hikayede veya oyununda yer alan kurgusal kişi veya yaratık." },
{ kelime: "atmosfer", ipucu: "Dünya'yı çevreleyen gaz tabakası." },
{ kelime: "kalibrasyon", ipucu: "Bir ölçüm cihazının doğruluğunu veya hassasiyetini ayarlama işlemi." },
{ kelime: "restorasyon", ipucu: "Bozulmuş veya hasar görmüş bir şeyi eski haline getirme süreci." },
{ kelime: "fotokopi", ipucu: "Bir belgenin kopyasını çıkarmak için kullanılan cihaz." },
{ kelime: "bürokrasi", ipucu: "Karmaşık ve sıkı yönetmeliklere dayalı devlet yönetimi." },
{ kelime: "literatür", ipucu: "Bir dilde yazılmış tüm edebi eserlerin genel adı." },
{ kelime: "prosedür", ipucu: "Belirli bir amacı elde etmek için izlenen yöntem veya adımlar." },
{ kelime: "deprem", ipucu: "Yer kabuğunda meydana gelen sismik hareket ve sarsıntı." },
{ kelime: "rezervasyon", ipucu: "Bir hizmeti veya yer ayırtma işlemi." },
{ kelime: "manevi", ipucu: "Duygusal veya ruhsal olarak maddi olmayan değerlerle ilgili." },
{ kelime: "organizasyon", ipucu: "Belirli bir amaç için düzenlenmiş yapı veya birlik." },
{ kelime: "haberdar", ipucu: "Bir durum hakkında bilgi sahibi olmak veya bilgi vermek." },
{ kelime: "katastrof", ipucu: "Feci ve yıkıcı bir olay veya durum." },
{ kelime: "koordinasyon", ipucu: "Farklı bileşenler arasında uyumlu çalışmayı sağlama." },
{ kelime: "dezenfekte", ipucu: "Mikroorganizmalardan arındırmak için temizleme işlemi." },
{ kelime: "istatistik", ipucu: "Verilerin toplanması, analizi ve yorumlanmasıyla ilgili bilim." },
{ kelime: "endüstriyel", ipucu: "Sanayiyle ilgili veya sanayi için yapılan." },
{ kelime: "kolaylaştırma", ipucu: "Bir süreci veya işlemi daha kolay ve etkili hale getirme." },
{ kelime: "paradoksal", ipucu: "Mantıksal olarak çelişen veya anlaşılmaz görünen." },
{ kelime: "propaganda", ipucu: "Bir fikri veya düşünceyi yaymak için yapılan bilinçli çaba." },
{ kelime: "rehabilitasyon", ipucu: "Sağlığın ve işlevin geri kazanılması için yapılan tedavi." },
{ kelime: "ritmik", ipucu: "Düzenli bir desen veya tekrarlayan hareketlerle ilgili." },
{ kelime: "kooperatif", ipucu: "Ortak amaçlar için bir araya gelen kişilerin oluşturduğu yapı." },
{ kelime: "ülkemiz", ipucu: "Konuşmacının ait olduğu ülkeyi ifade eden zamir." },
{ kelime: "hukuk", ipucu: "Toplumda düzeni sağlamak için oluşturulan kuralların tümü." },
{ kelime: "aktif", ipucu: "Enerjik veya hareketli olan." },
{ kelime: "tahmin", ipucu: "Gelecekte olabilecek bir olayı önceden kestirme eylemi." },
    { kelime: "gülümseme", ipucu: "Ağız ve yüz kaslarının hoş bir ifadeyle kıvrılması." },
    { kelime: "bilgisayar", ipucu: "Verileri işlemek, depolamak ve iletmek için tasarlanmış elektronik bir cihaz." },
    { kelime: "gitar", ipucu: "Tellerden çıkan müzik sesi ile çalınan bir enstrüman." },
    { kelime: "ayakkabı", ipucu: "Ayakları giyinmek veya korumak için giyilen başlık." },
    { kelime: "kalem", ipucu: "Yazı yazmak veya çizim yapmak için kullanılan araç." },
    { kelime: "şemsiye", ipucu: "Yağmur ve güneşten korunmak için kullanılan taşınabilir şey." },
    { kelime: "bulut", ipucu: "Gökyüzünde görülen su damlacıklarının veya buz kristallerinin topluluğu." },
    { kelime: "aile", ipucu: "Bir evde birlikte yaşayan ve aynı soydan gelen insanlar." },
    { kelime: "ev", ipucu: "Bir kişinin yaşamak veya barınmak için kullandığı yer." },
    { kelime: "renk", ipucu: "Görülen nesnelerin ışığı yansıtarak veya emerek oluşturduğu özellik." },
    { kelime: "pasta", ipucu: "Tatlı veya tuzlu içerikli fırında pişirilen yiyecek." },
    { kelime: "kütüphane", ipucu: "Kitapların saklandığı ve ödünç alındığı yer." },
    { kelime: "ay", ipucu: "Dünya'nın doğal uydusu olan gök cismi." },
    { kelime: "saç", ipucu: "Başın üst kısmında bulunan ve kıllardan oluşan yapı." },
    { kelime: "kağıt", ipucu: "Yazmak veya çizim yapmak için kullanılan ince malzeme." },
    { kelime: "masa", ipucu: "Yemek yemek, çalışmak veya eşyaları koymak için kullanılan mobilya." },
    { kelime: "hediye", ipucu: "Özel bir durumda verilen veya alınan armağan." },
    { kelime: "telefon", ipucu: "Çoğunlukla iletişim kurmak ve arama yapmak için kullanılan taşınabilir elektronik cihaz." },
    { kelime: "kamera", ipucu: "Görüntüleri yakalayan ve kaydeden optik cihaz." },
    { kelime: "ayna", ipucu: "Yansıma yapabilen cam veya metal kaplama." },
    { kelime: "bahçe", ipucu: "Bitkilerin yetiştirildiği ve süslenmek için kullanılan açık alan." },
    { kelime: "kelebek", ipucu: "Gündüz uçan, renkli ve kanatlı böcek." },
    { kelime: "pencere", ipucu: "Duvar veya çatıda açılan camlı boşluk." },
    { kelime: "yıldırım", ipucu: "Elektrik deşarjı nedeniyle oluşan parlak ve ani ışık." },
    { kelime: "kale", ipucu: "Genellikle bir şehri veya stratejik bir alanı korumak için yapılan yapı." },
    { kelime: "gemi", ipucu: "Denizde seyahat etmek için kullanılan büyük su aracı." },
    { kelime: "müzik", ipucu: "Seslerin ve ritimlerin düzenlenmesi ve ifade edilmesi sanatı." },
    { kelime: "pazar", ipucu: "Genellikle ticaret ve alışverişin yapıldığı belirli gün ve yer." },
    { kelime: "kuş", ipucu: "Genellikle uçan, tüylü ve yumurtlayan omurgalı hayvan." },
    { kelime: "gece", ipucu: "Güneşin batışından günün doğuşuna kadar süren dönem." },
    { kelime: "buz", ipucu: "Su soğuyup donduğunda oluşan katı durum." },
    { kelime: "güneş", ipucu: "Gündüz gökyüzünde ışık ve ısı sağlayan yıldız." },
    { kelime: "yol", ipucu: "Bir yerden diğerine ulaşmak için kullanılan genellikle açık alan." },
    { kelime: "oyun", ipucu: "Eğlenmek, rekabet etmek veya amaçlı etkinliklerle zaman geçirmek için yapılan faaliyet." },
    { kelime: "yemek", ipucu: "Yemek pişirmek ve yemek için kullanılan besinlerin genel adı." },
    { kelime: "ağaç", ipucu: "Odun veya yaprakları olan büyük bitki." },
    { kelime: "yazılım", ipucu: "Bilgisayarın çalışması için talimatları içeren programlar." },
    { kelime: "kitap", ipucu: "Birçok sayfası olan ve bilgi veya hikaye içeren basılı veya dijital yayın." },
    { kelime: "top", ipucu: "Genellikle yuvarlak ve çeşitli oyunlar için kullanılan spor aracı." },
    { kelime: "bulut", ipucu: "Gökyüzünde görülen su damlacıklarının veya buz kristallerinin topluluğu." },
    { kelime: "öğrenci", ipucu: "Okul veya üniversitede eğitim alan kişi." },
    { kelime: "hastane", ipucu: "Sağlık hizmetleri ve tıbbi tedavi sunan sağlık kurumu." },
    { kelime: "oyuncak", ipucu: "Eğlence veya oyun amaçlı kullanılan nesne veya araç." },
    { kelime: "kedi", ipucu: "Küçük, tüylü ve dört ayaklı evcil hayvan." },
    { kelime: "ses", ipucu: "Hava titreşimleri yoluyla duyulabilen ses veya seslerin oluşturduğu olay." },
    { kelime: "gözlük", ipucu: "Görme yeteneğini düzeltmek veya korumak için kullanılan optik araç." },
    { kelime: "rüya", ipucu: "Uyurken görülen hayal veya düş." },
    { kelime: "balık", ipucu: "Su içinde yaşayan omurgalı hayvanlar." },
    { kelime: "uçak", ipucu: "Hava yoluyla seyahat etmek için kullanılan hava aracı." },
    { kelime: "kum", ipucu: "Toprak parçacıklarının birikmesi sonucu oluşan ince tanecikli madde." },
    { kelime: "şarkı", ipucu: "Sesli bir şekilde ifade edilen müzik ve sözlerin birleşimi." },
    { kelime: "saat", ipucu: "Zamanı ölçmek için kullanılan cihaz." },
    { kelime: "çiçek", ipucu: "Bitkilerin rengarenk ve güzel görünümlü organı." },
    { kelime: "aşk", ipucu: "Yoğun duygusal bir bağ ve sevgi durumu." },
    { kelime: "yemek", ipucu: "Yemek pişirmek ve yemek için kullanılan besinlerin genel adı." },
    { kelime: "deniz", ipucu: "Tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "futbol", ipucu: "Topun bir takım arkadaşları arasında rakip takımın kalesine sokulması oyunu." },
    { kelime: "çanta", ipucu: "Taşımak için kullanılan torba benzeri eşya." },
    { kelime: "televizyon", ipucu: "Görüntü ve sesleri evde yayınlayan elektronik cihaz." },
    { kelime: "öğretmen", ipucu: "Eğitim veren ve öğrencilere rehberlik eden kişi." },
    { kelime: "araba", ipucu: "Motorlu taşıt, özellikle dört tekerlekli ve özel veya ticari kullanım için tasarlanmış olan." },
    { kelime: "çikolata", ipucu: "Kakao ve şekerden yapılan lezzetli tatlı." },
    { kelime: "gülümseme", ipucu: "Ağız ve yüz kaslarının hoş bir ifadeyle kıvrılması." },
    { kelime: "bilgisayar", ipucu: "Verileri işlemek, depolamak ve iletmek için tasarlanmış elektronik bir cihaz." },
    { kelime: "gitar", ipucu: "Tellerden çıkan müzik sesi ile çalınan bir enstrüman." },
    { kelime: "ayakkabı", ipucu: "Ayakları giyinmek veya korumak için giyilen başlık." },
    { kelime: "kalem", ipucu: "Yazı yazmak veya çizim yapmak için kullanılan araç." },
    { kelime: "şapka", ipucu: "Başın üstünü örtmek veya süslemek için giyilen aksesuar." },
    { kelime: "güneş gözlüğü", ipucu: "Gözleri güneş ışınlarından korumak için kullanılan gözlük." },
    { kelime: "bisiklet", ipucu: "İki tekerlekli, insan gücüyle hareket ettirilen ulaşım aracı." },
    { kelime: "deniz", ipucu: "Tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "gezegen", ipucu: "Güneş veya yıldızların etrafında dönen gök cismi." },
    { kelime: "ağaç", ipucu: "Odun veya yaprakları olan büyük bitki." },
    { kelime: "hobi", ipucu: "Boş zamanlarda yapılan, ilgi ve zevk veren etkinlik." },
    { kelime: "gazete", ipucu: "Günlük haberlerin, makalelerin ve reklamların yayınlandığı basılı yayın." },
    { kelime: "teleskop", ipucu: "Uzak gök cisimlerini gözlemlemek için kullanılan optik araç." },
    { kelime: "denizyıldızı", ipucu: "Deniz altında yaşayan, kolları olan omurgasız hayvan." },
    { kelime: "tiyatro", ipucu: "Oyuncular tarafından canlandırılan sahne performanslarının sergilendiği yer." },
    { kelime: "kamyon", ipucu: "Yük taşımak için kullanılan büyük taşıt aracı." },
    { kelime: "kepçe", ipucu: "Toprak, kum veya diğer malzemeleri kaldırmak için kullanılan araç." },
    { kelime: "meyve", ipucu: "Genellikle tatlı ve yenilebilir bitki ürünü." },
    { kelime: "radyo", ipucu: "Sesli yayınları almak ve dinlemek için kullanılan cihaz." },
    { kelime: "dans", ipucu: "Müziğe uygun olarak vücut hareketleri yapma sanatı veya eğlencesi." },
    { kelime: "çamaşır", ipucu: "Giysilerin yıkanarak temizlenmesi için kullanılan eşya." },
    { kelime: "bisiklet", ipucu: "İki tekerlekli, insan gücüyle hareket ettirilen ulaşım aracı." },
    { kelime: "deniz", ipucu: "Tuzlu su kütleleri tarafından kaplanmış büyük arazi parçası." },
    { kelime: "gezegen", ipucu: "Güneş veya yıldızların etrafında dönen gök cismi." },
    { kelime: "ağaç", ipucu: "Odun veya yaprakları olan büyük bitki." },
    { kelime: "hobi", ipucu: "Boş zamanlarda yapılan, ilgi ve zevk veren etkinlik." },
    { kelime: "gazete", ipucu: "Günlük haberlerin, makalelerin ve reklamların yayınlandığı basılı yayın." },
    { kelime: "teleskop", ipucu: "Uzak gök cisimlerini gözlemlemek için kullanılan optik araç." },
    { kelime: "denizyıldızı", ipucu: "Deniz altında yaşayan, kolları olan omurgasız hayvan." },
    { kelime: "tiyatro", ipucu: "Oyuncular tarafından canlandırılan sahne performanslarının sergilendiği yer." },
    { kelime: "kamyon", ipucu: "Yük taşımak için kullanılan büyük taşıt aracı." },
    { kelime: "kepçe", ipucu: "Toprak, kum veya diğer malzemeleri kaldırmak için kullanılan araç." },
    { kelime: "meyve", ipucu: "Genellikle tatlı ve yenilebilir bitki ürünü." },
    { kelime: "radyo", ipucu: "Sesli yayınları almak ve dinlemek için kullanılan cihaz." },
    { kelime: "dans", ipucu: "Müziğe uygun olarak vücut hareketleri yapma sanatı veya eğlencesi." },
    { kelime: "çamaşır", ipucu: "Giysilerin yıkanarak temizlenmesi için kullanılan eşya." },
    { kelime: "patlamış mısır", ipucu: "Mısırın ısıtılarak patlatılmasıyla elde edilen atıştırmalık." },
{ kelime: "sosyal medya", ipucu: "İnternet üzerinde insanlar arasında etkileşimi sağlayan platformlar." },
{ kelime: "bürokratik", ipucu: "Karmaşık ve sıkı yönetmeliklere dayalı devlet yönetimi ile ilgili." },
{ kelime: "televizyon", ipucu: "Görüntü ve sesleri evde yayınlayan elektronik cihaz." },
{ kelime: "organizasyon", ipucu: "Belirli bir amaç için düzenlenmiş yapı veya birlik." },
{ kelime: "yürütme", ipucu: "Bir planın, kararın veya görevin uygulanma süreci." },
{ kelime: "toplantı", ipucu: "Kişilerin bir araya gelerek görüş alışverişinde bulunduğu etkinlik." },
{ kelime: "psikolojik", ipucu: "Zihinsel ve duygusal süreçlerle ilgili." },
{ kelime: "elektronik", ipucu: "Elektriksel devreler ve bileşenler kullanılarak çalışan teknoloji." },
{ kelime: "parlamenter", ipucu: "Hükümet sistemiyle ilgili veya parlamenterlere ait." },
{ kelime: "konferans", ipucu: "Bir konuda bilgi ve deneyimlerin paylaşıldığı toplantı." },
{ kelime: "memnuniyet", ipucu: "Bir şeyle veya bir durumla tatmin ve hoşnut olma hali." },
{ kelime: "destek", ipucu: "Bir kişiye veya bir şeye yardım sağlama veya destek olma." },
{ kelime: "strateji", ipucu: "Uzun vadeli hedeflere ulaşmak için planlama ve hareket etme." },
{ kelime: "çözünürlük", ipucu: "Bir görüntünün veya ekranın detay düzeyi." },
{ kelime: "konsept", ipucu: "Bir fikrin veya tasarımın temel kavramı veya düşünce." },
{ kelime: "genelge", ipucu: "Yönetim veya otoriteden gelen resmi bildiri veya talimat." },
{ kelime: "rejenerasyon", ipucu: "Yenilenme veya iyileşme süreci." },
{ kelime: "modernizasyon", ipucu: "Geleneksel bir şeyi çağdaş standartlara göre güncelleme süreci." },
{ kelime: "perspektif", ipucu: "Bir nesneyi veya durumu belirli bir bakış açısıyla değerlendirme." },
{ kelime: "haberdarlık", ipucu: "Bir konuda bilgi sahibi olma durumu." },

{ kelime: "elektrikli", ipucu: "Elektrik enerjisiyle çalışan veya çalışan cihaz veya araç." },
{ kelime: "kontrat", ipucu: "İki veya daha fazla taraf arasında yapılan resmi anlaşma." },
{ kelime: "kişisel", ipucu: "Bir kişiye özgü veya onunla ilgili olan." },
{ kelime: "mekanik", ipucu: "Makine ve cihazların fiziksel prensiplere dayanan çalışması." },
{ kelime: "kavramsal", ipucu: "Kavramlarla ve düşüncelerle ilgili olan." },
{ kelime: "malzeme", ipucu: "Bir ürünün yapımında kullanılan madde veya materyal." },
{ kelime: "çalışkanlık", ipucu: "Çalışma ve çaba gösterme niteliği." },
{ kelime: "harmoni", ipucu: "Uyumlu bir şekilde bir araya gelme ve uyum oluşturma durumu." },

{ kelime: "milliyetçilik", ipucu: "Bir millete aidiyet ve bağlılık duygusu." },
{ kelime: "dönüşüm", ipucu: "Bir şeyin biçimini veya yapıını değiştirme süreci." },
{ kelime: "parlamento", ipucu: "Temsilcilerin toplandığı ve yasama görevini yaptığı meclis." },
{ kelime: "organik", ipucu: "Doğal veya kimyasal katkı maddesi olmadan üretilen." },
{ kelime: "gelişim", ipucu: "Bir organizmanın veya sürecin olgunlaşma veya ilerleme süreci." },
{ kelime: "tedbir", ipucu: "Tehlikeden veya olumsuz durumlardan korunmak için alınan önlem." },
{ kelime: "yalıtım", ipucu: "Dış etkilerden korunmak için bir şeyin izole edilmesi." },
{ kelime: "karakteristik", ipucu: "Belirli bir şeyi veya kişiyi tanımlayan özellik veya nitelik." },
{ kelime: "potansiyel", ipucu: "Henüz gerçekleşmemiş ama mümkün olan durum veya kabiliyet." },
{ kelime: "kapasite", ipucu: "Bir şeyi yapma veya depolama yeteneği." },
{ kelime: "muhalefet", ipucu: "Hükümete veya mevcut düzene karşı olan grup veya kişiler." },
{ kelime: "temel", ipucu: "En önemli veya ana olan şey." },
{ kelime: "kararlılık", ipucu: "Sürekli ve istikrarlı olma durumu." },
{ kelime: "anlamlandırma", ipucu: "Bir şeyin anlamını çıkarma veya yorumlama süreci." },
{ kelime: "vazgeçilmez", ipucu: "Vazgeçilmesi zor veya imkansız olan şey." },

{ kelime: "haberleşme", ipucu: "Bilgi veya mesajların aktarılması veya iletilmesi süreci." },
{ kelime: "entegrasyon", ipucu: "Farklı bileşenleri bir araya getirme ve birlikte çalışma süreci." },
{ kelime: "rehberlik", ipucu: "Bir kişinin yol gösterme ve destek sağlama süreci." },
{ kelime: "olumsuzluk", ipucu: "Olumsuz veya olumsuz bir durum veya etki." },
{ kelime: "marjinal", ipucu: "Ana akımdan veya sıradan olandan ayrılan veya farklı olan." },
{ kelime: "hibernasyon", ipucu: "Soğuk dönemlerde vücut aktivitesini düşürerek uyku durumuna geçme." },
{ kelime: "proje", ipucu: "Belirli bir amacı gerçekleştirmek için planlanmış çalışma." },
{ kelime: "inovasyon", ipucu: "Yenilik ve farklılık yaratma süreci." },
{ kelime: "fikir", ipucu: "Bir düşünce, görüş veya düşünce." },
{ kelime: "hatırlama", ipucu: "Geçmiş olayları veya bilgileri zihinde canlandırma süreci." },
{ kelime: "operasyon", ipucu: "Bir görevi veya işlemi gerçekleştirme süreci." },
{ kelime: "laiklik", ipucu: "Din ve devlet işlerinin ayrı olduğu düzen." },
{ kelime: "kongre", ipucu: "Temsilcilerin bir araya gelerek toplandığı toplantı." },
{ kelime: "liman", ipucu: "Gemilerin yanaşarak yük indirip bindirdiği su kenarı alan." },
{ kelime: "öğrenim", ipucu: "Bilgi ve becerilerin edinildiği eğitim süreci." },
{ kelime: "toplumsal", ipucu: "Toplumla ilgili veya toplum tarafından paylaşılan." },
{ kelime: "gereksinim", ipucu: "Bir şeye olan ihtiyaç veya zorunluluk." },
{ kelime: "kalifikasyon", ipucu: "Belirli bir iş veya görev için gerekli nitelik veya yetenek." },


{ kelime: "aritmetik", ipucu: "Sayılarla ilgili temel hesaplamalar ve işlemler." },
{ kelime: "plagiyat", ipucu: "Başka bir kişinin fikirlerini, yazılarını veya eserlerini kopyalama ve sahiplenme." },
{ kelime: "harabeler", ipucu: "Yıkılmış veya terk edilmiş yapıların kalıntıları." },
{ kelime: "ambrosia", ipucu: "Mitolojide tanrıların yediği ebedi yaşam iksiri." },
{ kelime: "idrak", ipucu: "Bir şeyin anlaşılması veya kavranması." },
{ kelime: "kanonik", ipucu: "Genellikle kabul edilen, otorite tarafından onaylanan veya standarda uygun olan." },
{ kelime: "otokrasi", ipucu: "Tek bir kişinin mutlak ve tek başına yönettiği hükümet biçimi." },
{ kelime: "paternalist", ipucu: "Otoriter bir biçimde insanlara rehberlik etmeye çalışan veya onlara yönlendiren kişi." },
{ kelime: "retorik", ipucu: "Etkileyici ve güçlü dil kullanımıyla duyguları etkilemeye yönelik." },
{ kelime: "hologram", ipucu: "Üç boyutlu görüntülerin kaydedildiği ve yeniden oluşturulduğu optik araç." },
{ kelime: "solüsyon", ipucu: "Bir sıvıda veya gazda başka bir maddeyi çözen karışım." },
{ kelime: "hezeyan", ipucu: "Gerçekle uyumsuz ve hayali duygu ve düşüncelerin yaşandığı zihinsel durum." },
{ kelime: "ornitoloji", ipucu: "Kuşların bilimsel olarak incelendiği ornitoloji alanı." },
{ kelime: "filantropi", ipucu: "İnsanlığın iyiliği için cömertçe bağış yapma veya destek sağlama eylemi." },
{ kelime: "trajikomik", ipucu: "Hem trajik hem de komik unsurları içeren veya birleştiren." },
{ kelime: "hipotez", ipucu: "Bir olayı veya olguyu açıklamak için yapılan geçici bir açıklama veya tahmin." },
{ kelime: "periferik", ipucu: "Merkeze veya temele göre daha az önemli veya daha uzakta olan." },
{ kelime: "inovatif", ipucu: "Yenilikçi ve yaratıcı bir biçimde düşünen veya hareket eden." },
{ kelime: "paradoksal", ipucu: "Mantıksal olarak çelişen veya anlaşılmaz görünen." },
{ kelime: "pratik", ipucu: "Teoriden çok gerçek dünya uygulamalarına odaklanan." },
{ kelime: "retrospektif", ipucu: "Geçmişe yönelik, geçmişi hatırlatan veya inceleyen." },
{ kelime: "refleksiyon", ipucu: "Düşüncelerin, deneyimlerin veya olayların üzerine düşünme ve değerlendirme." },
{ kelime: "kapris", ipucu: "Ani ve değişken bir biçimde sergilenen istek veya davranış." },
{ kelime: "kolonyalizm", ipucu: "Bir devletin sömürgeci politikalarla başka bölgeleri kontrol "}


]